package mariobros;

import ListaObjetos.Lista;
import ListaObjetos.Objeto;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Objetos.*;
import ListaObjetos.*;
import mariobros.*;

public class CargaDeObjetos extends javax.swing.JFrame {
    
    public ImageIcon iconoBloque, iconoSuelo, iconoGoomba, iconoKoopa, iconoFicha, iconoHongo, iconoMario, iconoCastillo; 
    private Lista lista;
    public Mario mario;
    public Castillo castillo;
    public String tipo, nombre;
    public ImageIcon icono;
    
    public CargaDeObjetos() {
        initComponents();
        iconoBloque = new ImageIcon("C:\\Users\\Elmer\\Documents\\NetBeansProjects\\MarioBros\\src\\mariobros\\pared2.jpg");
        iconoSuelo = new ImageIcon("C:\\Users\\Elmer\\Documents\\NetBeansProjects\\MarioBros\\src\\mariobros\\Suelo2.jpg");
        iconoGoomba = new ImageIcon("C:\\Users\\Elmer\\Documents\\NetBeansProjects\\MarioBros\\src\\mariobros\\Goomba2.png");
        iconoKoopa = new ImageIcon("C:\\Users\\Elmer\\Documents\\NetBeansProjects\\MarioBros\\src\\mariobros\\Koopa2.jpg");
        iconoFicha = new ImageIcon("C:\\Users\\Elmer\\Documents\\NetBeansProjects\\MarioBros\\src\\mariobros\\Ficha2.jpg");
        iconoHongo = new ImageIcon("C:\\Users\\Elmer\\Documents\\NetBeansProjects\\MarioBros\\src\\mariobros\\Hongo2.jpg");
        iconoMario = new ImageIcon("C:\\Users\\Elmer\\Documents\\NetBeansProjects\\MarioBros\\src\\mariobros\\Mario2.jpg");
        iconoCastillo = new ImageIcon("C:\\Users\\Elmer\\Documents\\NetBeansProjects\\MarioBros\\src\\mariobros\\Castillo2.jpg");
        HabilitarComponentes(false);
        lista = new Lista();
    }
    
    public void HabilitarComponentes(boolean bool){
        cbx_TipoObjeto.setEnabled(bool);
        btn_Agregar.setEnabled(bool);
        txt_Nombre.setEnabled(bool);
    }
    
    public ImageIcon getIcono(){
            if(cbx_TipoObjeto.getSelectedItem().equals("Mario")){
                this.icono = iconoMario;
                this.mario.setCantidad(1);
            }
            if(cbx_TipoObjeto.getSelectedItem().equals("Castillo")){
                this.icono = iconoCastillo;
                this.castillo.setCantidad(1);
            }
            if(cbx_TipoObjeto.getSelectedItem().equals("Suelo")){
                this.icono = iconoSuelo;
            }
            if(cbx_TipoObjeto.getSelectedItem().equals("Bloque")){
                this.icono = iconoBloque;
            }
            if(cbx_TipoObjeto.getSelectedItem().equals("Goomba")){
                this.icono = iconoGoomba;
            }
            if(cbx_TipoObjeto.getSelectedItem().equals("Koopa")){
                this.icono = iconoKoopa;
            }
            if(cbx_TipoObjeto.getSelectedItem().equals("Ficha")){
                this.icono = iconoFicha;
            }
            if(cbx_TipoObjeto.getSelectedItem().equals("Hondo de Vida")){
      
          this.icono = iconoHongo;
            }
            
            return icono;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbx_TipoObjeto = new javax.swing.JComboBox();
        lbl_ImagenMuestra = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_Agregar = new javax.swing.JButton();
        btn_Nuevo = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carga De Objetos");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jLabel5.setFont(new java.awt.Font("Angsana New", 3, 36)); // NOI18N
        jLabel5.setText("Elige los objetos que...");

        jLabel1.setFont(new java.awt.Font("Angsana New", 3, 24)); // NOI18N
        jLabel1.setText("quieres que aparezcan en el juego");

        cbx_TipoObjeto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suelo", "Bloque", "Goomba", "Koopa", "Ficha", "Hongo de Vida", "Mario", "Castillo" }));
        cbx_TipoObjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_TipoObjetoMouseClicked(evt);
            }
        });
        cbx_TipoObjeto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_TipoObjetoItemStateChanged(evt);
            }
        });

        lbl_ImagenMuestra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mariobros/suelo2.jpg"))); // NOI18N
        lbl_ImagenMuestra.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Angsana New", 3, 24)); // NOI18N
        jLabel3.setText("Nombre:");

        btn_Agregar.setFont(new java.awt.Font("Angsana New", 3, 24)); // NOI18N
        btn_Agregar.setText("Agregar");
        btn_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AgregarMouseClicked(evt);
            }
        });
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        btn_Nuevo.setFont(new java.awt.Font("Angsana New", 3, 24)); // NOI18N
        btn_Nuevo.setText("Nuevo");
        btn_Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NuevoMouseClicked(evt);
            }
        });
        btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevoActionPerformed(evt);
            }
        });

        btn_Salir.setFont(new java.awt.Font("Angsana New", 3, 24)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_TipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ImagenMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_Nuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Salir))
                            .addComponent(jLabel3)
                            .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbx_TipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ImagenMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Agregar)
                            .addComponent(btn_Nuevo)
                            .addComponent(btn_Salir))))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void cbx_TipoObjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_TipoObjetoMouseClicked
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_cbx_TipoObjetoMouseClicked

    private void cbx_TipoObjetoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_TipoObjetoItemStateChanged
        // TODO add your handling code here:
        if(cbx_TipoObjeto.getSelectedItem().equals("Bloque")==true){
            lbl_ImagenMuestra.setIcon(iconoBloque);
        }
        if(cbx_TipoObjeto.getSelectedItem().equals("Suelo")==true){
            lbl_ImagenMuestra.setIcon(iconoSuelo);
        }
        if(cbx_TipoObjeto.getSelectedItem().equals("Goomba")==true){
            lbl_ImagenMuestra.setIcon(iconoGoomba);
        }
        if(cbx_TipoObjeto.getSelectedItem().equals("Koopa")==true){
            lbl_ImagenMuestra.setIcon(iconoKoopa);
        }
        if(cbx_TipoObjeto.getSelectedItem().equals("Hongo de Vida")==true){
            lbl_ImagenMuestra.setIcon(iconoHongo);
        }
        if(cbx_TipoObjeto.getSelectedItem().equals("Ficha")==true){
            lbl_ImagenMuestra.setIcon(iconoFicha);
        }
        if(cbx_TipoObjeto.getSelectedItem().equals("Mario")==true){
            lbl_ImagenMuestra.setIcon(iconoMario);
        }
        if(cbx_TipoObjeto.getSelectedItem().equals("Castillo")==true){
            lbl_ImagenMuestra.setIcon(iconoCastillo);
        }
    }//GEN-LAST:event_cbx_TipoObjetoItemStateChanged

    private void btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NuevoActionPerformed

    private void btn_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_SalirMouseClicked

    private void btn_NuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NuevoMouseClicked
        try{
           this.lista=new Lista();
           JOptionPane.showMessageDialog(this, "Lista Creada");
           HabilitarComponentes(true); 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al crear lista: " + e);
        }
    }//GEN-LAST:event_btn_NuevoMouseClicked

    private void btn_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgregarMouseClicked
        try{
            this.tipo = cbx_TipoObjeto.getSelectedItem().toString();
            this.nombre = txt_Nombre.getText();
            this.icono = this.getIcono();
            
            if(mario.getCantidad()==1){
                JOptionPane.showMessageDialog(null, "No puedes agregar más de un Mario Bros");
            }
            if(castillo.getCantidad()==1){
                JOptionPane.showMessageDialog(null, "No puedes agregar más de un Castillo");
            }
            
            this.lista.Agregar(new Objeto(nombre, tipo, icono));
            JOptionPane.showMessageDialog(null, "El número de jugadores es " + this.lista.Length());
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al agregar objeto: "+e);
        }
    }//GEN-LAST:event_btn_AgregarMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargaDeObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargaDeObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargaDeObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargaDeObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargaDeObjetos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Nuevo;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JComboBox cbx_TipoObjeto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_ImagenMuestra;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
